title: ZiArt MakeCode Class
email: fzhang00@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This site was created to collect all of our project done in our MakeCode class. 
theme: jekyll-theme-architect
